In [1]:
import pandas as pd
import numpy as np
import re

## **Importing the CSV file**

In [2]:
df = pd.read_csv(r"C:\Users\ooha2\OneDrive\Desktop\EDA_Project\Gynaecologist Cleaning Conversion.csv")
df

,Unnamed: 0,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,0.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,0.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,0.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,0.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",0.0,0.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0,02:00
699,699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,0.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

## **Dropping the extra columns(unnamed:0) from DataFrame**

In [3]:
df.drop(columns='Unnamed: 0',inplace =True)

In [4]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,0.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,0.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,0.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,0.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",0.0,0.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,0.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

## **Adding new column that is Total Fee**

In [5]:
df['Total Fee'] = df['Fee at clinic'] + df['Online Fee']

## **Checking for new column whether it has been added or not**

In [6]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300.0,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800.0,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,0.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500.0,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,0.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500.0,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000.0,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,0.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500.0,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,0.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500.0,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600.0,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",0.0,0.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0.0,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,0.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450.0,04:30

## **Checking Null Values**

In [7]:
df.isnull().sum()

Name                        0
Specialization              0
Experience (in years)       0
Education                   0
Fee at clinic               0
Online Fee                  0
Clinic Name                 0
Area                        0
Available From              0
Available Till              0
City                        0
Total Fee                   0
Number of Hrs. Available    0
dtype: int64

## **Checking Total Null Values of Experience(in years),Education,Fee at Clinic,Online Fee,Clinic Fee,Area,Total Fee**

* by seeing the above output we can say that there are `null values in 7 columns`.

In [8]:
df[df['Experience (in years)'].isnull() |
df['Education'].isnull() | 
df['Fee at clinic'].isnull() |
df['Online Fee'].isnull() |
df['Clinic Name'].isnull() |
df['Area'].isnull() |
df['Total Fee'].isnull()]
# 462 null count of all columns

Empty DataFrame
Columns: [Name, Specialization, Experience (in years), Education, Fee at clinic, Online Fee, Clinic Name, Area, Available From, Available Till, City, Total Fee, Number of Hrs. Available]
Index: []

In [9]:
## Checking All column names
df.columns

Index(['Name', 'Specialization', 'Experience (in years)', 'Education',
       'Fee at clinic', 'Online Fee', 'Clinic Name', 'Area', 'Available From',
       'Available Till', 'City', 'Total Fee', 'Number of Hrs. Available'],
      dtype='object')

## **Filling Null Values with `0`,`Unknown` and `Not Mentioned` and Data Type Conversion**

In [10]:
# filling experience null values with Not Mentioned
df['Experience (in years)']=df['Experience (in years)'].fillna(0)

In [11]:
# filling education null values with Not Mentioned
df['Education']=df['Education'].fillna('Not Mentioned')

### Conversion of `Fee at clinic` column from object to numeric

- Removing `â‚¹ ` from the columns so the column can be converted to numerical type
- Converting datatype of the column using `pd.to_numeric() method`

In [12]:
# replacing clinic fee rupees symbol with space
df['Fee at clinic']=df['Fee at clinic'].replace('â‚¹',' ') 

# Converting categorical to numerical
df['Fee at clinic']=pd.to_numeric(df['Fee at clinic'])

# filling fee at clinic null values with unknown
df['Fee at clinic']=df['Fee at clinic'].fillna(0)

## **Conversion of `Online Fee` column from object to numeric**

- Removing `â‚¹ ` from the columns so the column can be converted to numerical type
- Converting datatype of the column using `pd.to_numeric() method`

In [13]:
# replacing online fee rupees symbol with space
df['Online Fee']=df['Online Fee'].replace('â‚¹',' ') 

# Converting categorical to numerical
df['Online Fee']=pd.to_numeric(df['Online Fee'])

# filling online fee null values with 'zero'
df['Online Fee']=df['Online Fee'].fillna(300)

In [14]:
# filling clinic name null values with unknown
df['Clinic Name']=df['Clinic Name'].fillna('Unknown')

In [15]:
# filling Area null values with unknown
df['Area']=df['Area'].fillna('Unknown')

## **Adding new column Total Fee**
- using sum of `Online Fee` and `Fee at clinic` columns

In [16]:
# Adding new Column
df['Total Fee'] = df['Fee at clinic'] + df['Online Fee']

# Format Total Fee as currency
df['Total Fee'] = 'â‚¹ ' + df['Total Fee'].astype(int).astype(str)

# replacing Total fee rupees symbol with space
df['Total Fee']=df['Total Fee'].str.replace('â‚¹',' ') 
df['Total Fee']=pd.to_numeric(df['Total Fee'])

## **converting Timing columns to datetime object**
1. Converting `Available From` and `Available Till` columns to datetime format.

In [18]:
df['Available From'] = pd.to_datetime(df['Available From'], format='%I:%M %p').dt.time
df['Available Till'] = pd.to_datetime(df['Available Till'], format='%I:%M %p').dt.time

ValueError: time data "10:00:00" doesn't match format "%I:%M %p", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

## **Creating New Column Number of Hrs Available**

1. Creating new column `Number of Hrs. Available` to show total number of hours of availability by subtracting time delta of `Available Till`  from time delta of `Available From`
2. Removing days part from the `Number of Hrs. Available` column

In [19]:
# Adding new column i.e., Adding Numbers of Hrs.Available
df['Number of Hrs. Available'] = (pd.to_timedelta(df['Available Till'].astype(str)) - pd.to_timedelta(df['Available From'].astype(str)))

In [20]:
hrs = []
for i in df['Number of Hrs. Available'] :
    b = re.findall(r'days (.+):00$',str(i))
    if len(b) > 0 :
        if b[0][0] == '+' :
            hrs.append(b[0][1:])
        else :
            hrs.append(b[0])
    else :
        hrs.append(i)

In [21]:
df['Number of Hrs. Available'] = hrs

In [22]:
df.rename({'Number of Hrs. Available' : 'Number of Hrs. Available (HH:MM)'},inplace = True)

In [23]:
twelve_hr = df[pd.to_datetime(df['Number of Hrs. Available']).dt.hour <= 12]

C:\Users\ooha2\AppData\Local\Temp\ipykernel_7608\820136207.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  twelve_hr = df[pd.to_datetime(df['Number of Hrs. Available']).dt.hour <= 12]

In [24]:
twelve_hr['Number of Hrs. Available'].unique()

array(['08:00', '10:00', '03:00', '09:30', '06:00', '05:00', '07:00',
       '03:30', '05:45', '04:30', '09:00', '02:30', '04:00', '07:30',
       '02:00', '01:00', '00:00', '02:15', '00:30', '01:30', '06:30',
       '00:15'], dtype=object)

In [25]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,0.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,0.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,0.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,0.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",0.0,0.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,0.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

In [26]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,0.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,0.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,0.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,0.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",0.0,0.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,0.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

In [27]:
for i in df['Clinic Name'] :
    if type(i) == str :
        if i[0] == 'â‚¹' :
            print(i)

â‚¹ 1
â‚¹ 1
â‚¹ 1
â‚¹ 1
â‚¹ 1
â‚¹ 1
â‚¹ 1

In [28]:
for i in df['Area'] :
    if type(i) == str :
        if i[0] == '0' :
            print(i)

000 onlineEVA Care Clinic- The Every Woman?s Clinic
000 onlineEVA Care Clinic- The Every Woman?s Clinic
000 onlineEVA Care Clinic- The Every Woman?s Clinic
000 onlineEVA Care Clinic- The Every Woman?s Clinic
000 onlineEVA Care Clinic- The Every Woman?s Clinic
000 onlineEVA Care Clinic- The Every Woman?s Clinic
000 onlineEVA Care Clinic- The Every Woman?s Clinic

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 0 to 699
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      700 non-null    object
 1   Specialization            700 non-null    object
 2   Experience (in years)     700 non-null    float64
 3   Education                 700 non-null    object
 4   Fee at clinic             700 non-null    float64
 5   Online Fee                700 non-null    float64
 6   Clinic Name               700 non-null    object
 7   Area                      700 non-null    object
 8   Available From            700 non-null    object
 9   Available Till            700 non-null    object
 10  City                      700 non-null    object
 11  Total Fee                 700 non-null    int64
 12  Number of Hrs. Available  700 non-null    object
dtypes: float64(3), int64(1), object(9)
memory usage: 76.6+ KB

## **Checking Duplicates**

In [30]:
df[df.duplicated()]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
100,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
101,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
102,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,0.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
103,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,0.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
104,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,0.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,0.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",0.0,0.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,0.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

##  **Counting duplicate rows**

In [31]:
d_count = df.duplicated().sum()
print(f'Total duplicate rows: {d_count}')

Total duplicate rows: 600

## **Checking for duplicates in each column**

In [32]:
d_count_column = {col: df[col].duplicated().sum() for col in df.columns}

## **Displaying columns with duplicates**

In [33]:
duplicates_with_count = {col: count for col, count in d_count_column.items() if count > 0}
print("Columns with duplicates and their counts:")
print(duplicates_with_count)

Columns with duplicates and their counts:
{'Name': 600, 'Specialization': 699, 'Experience (in years)': 659, 'Education': 644, 'Fee at clinic': 685, 'Online Fee': 690, 'Clinic Name': 609, 'Area': 659, 'Available From': 680, 'Available Till': 677, 'City': 699, 'Total Fee': 678, 'Number of Hrs. Available': 677}

In [34]:
area = []
for i in df['Area'] :
    if re.findall(r'^\d+',i) :
        area.append(np.nan)
    elif re.findall(r'^www.',i) or i == 'S':
        area.append(np.nan)
    elif i == 'Bang' :
        area.append('Bangalore')
    else :
        area.append(i)

In [35]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,0.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,0.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,0.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,0.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",0.0,0.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,0.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

In [36]:
clinic_name = []
for i in df['Clinic Name'] :
    if re.findall(r'^\d+',i) :
        area.append(np.nan)
    elif re.findall(r'^www.',i) or i == 'S':
        area.append(np.nan)
    elif i == 'Bang' :
        area.append('Bangalore')
    else :
        area.append(i)

In [37]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,0.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,0.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,0.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,0.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",0.0,0.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,0.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

In [38]:
df['Online Fee'] = np.where(df['Online Fee'] == 0, 300, df['Online Fee'])
df['Fee at clinic'] = np.where(df['Fee at clinic'] == 0, 500, df['Fee at clinic'])

In [39]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,300.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,300.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,300.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,300.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",500.0,300.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,0,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,300.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

In [40]:
df.loc[df['Total Fee'] == 0, 'Total Fee'] = df.loc[df['Total Fee'] == 0, 'Fee at clinic'] + df.loc[df['Total Fee'] == 0, 'Online Fee']

In [41]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,300.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,300.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,300.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,300.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",500.0,300.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,800,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,300.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

In [45]:
df.drop(df.index[[8, 108, 208, 308, 408, 508, 608]],inplace = True)

In [46]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Sindhuri Kapu,Gynaecologist,13.0,"MBBS, DNB - Obstetrics & Gynecology",800.0,500.0,Ankura Hospital for Women & Children - Banjara...,Hyderabad,10:00:00,18:00:00,Hyderabad,1300,08:00
1,Dr. Juhul Arvind Patel,Gynaecologist,8.0,"DNB, DGO, Dip. Hospital Administration, Diplom...",500.0,300.0,Pristyn Care,Hyderabad,10:00:00,20:00:00,Hyderabad,800,10:00
2,Dr. Paipuru,Gynaecologist,0.0,Not Mentioned,500.0,300.0,Pristyn Care Clinic,Banjara Hills,17:00:00,20:00:00,Hyderabad,500,03:00
3,Dr M Swapna Reddy,Gynaecologist,17.0,"MBBS, DGO",500.0,300.0,Pristyn care,Hyderabad,09:00:00,18:30:00,Hyderabad,500,09:30
4,Dr. Sadhvi Reddy,Gynaecologist,14.0,"Fellowship In Minimal Access Surgery, MS - Ob...",500.0,500.0,Vijay Hospital,Dilsukhnagar,11:00:00,17:00:00,Hyderabad,1000,06:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Dr. Nivedita,Gynaecologist,25.0,"MBBS, MD - Obstetrics & Gynaecology",500.0,300.0,Srishti Women's CLinic (On Call),Tarnaka,10:00:00,17:00:00,Hyderabad,500,07:00
696,Dr. Neelima,Gynaecologist,28.0,"MBBS, MD - Obstetrics & Gynaecology, Fellowshi...",500.0,300.0,Neelima Hospital,Moti Nagar,10:00:00,14:00:00,Hyderabad,500,04:00
697,Anusha Patel,Gynaecologist,14.0,"MBBS, MS OBG",300.0,300.0,Habsiguda Polyclinic,Hyderabad,17:00:00,20:00:00,Hyderabad,600,03:00
698,Dr. Manjula Anagani,Gynaecologist,33.0,"MBBS, Internship, MD (Pathology), MD (Gynaecol...",500.0,300.0,Unknown,Unknown,11:00:00,13:00:00,Hyderabad,800,02:00
699,Dr. K Padmaja Devi,Gynaecologist,33.0,"MBBS, DGO",450.0,300.0,Sneha Clinics,KPHB,09:00:00,13:30:00,Hyderabad,450,04:30

In [47]:
df.to_csv('finalcopy_304_305_gynecologist_complete_cleaning.csv')